from django.urls import path

from .views import (
    AssignDailyTasksView,
    AuthMeView,
    CompleteTaskView,
    DailyChallengeView,
    DailyTasksView,
    EquipBadgeView,
    ForgotPasswordView,
    GameDailyRemainingView,
    GameStartView,
    GameSubmitView,
    HelloView,
    JournalHistoryView,
    JournalView,
    LeaderboardView,
    LoginView,
    PushSubscriptionView,
    RefreshTokenView,
    RegisterView,
    ResetPasswordView,
    SeedTasksView,
    UpdateFocusCategoryView,
    UpdateNameView,
    UserView,
    WeeklyWarReportView,
)

urlpatterns = [
    path("hello/", HelloView.as_view(), name="hello"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/forgot-password/", ForgotPasswordView.as_view(), name="auth-forgot-password"),
    path("auth/reset-password/", ResetPasswordView.as_view(), name="auth-reset-password"),
    path("auth/refresh/", RefreshTokenView.as_view(), name="auth-refresh"),
    path("auth/me/", AuthMeView.as_view(), name="auth-me"),
    path("daily-challenge/", DailyChallengeView.as_view(), name="daily-challenge"),
    path("game/remaining/", GameDailyRemainingView.as_view(), name="game-remaining"),
    path("game/start/", GameStartView.as_view(), name="game-start"),
    path("game/submit/", GameSubmitView.as_view(), name="game-submit"),
    path("complete-task/", CompleteTaskView.as_view(), name="complete-task"),
    path("user/", UserView.as_view(), name="user"),
    path("user/equip-badge/", EquipBadgeView.as_view(), name="equip-badge"),
    path("user/update-name/", UpdateNameView.as_view(), name="user-update-name"),
    path("user/update-focus/", UpdateFocusCategoryView.as_view(), name="user-update-focus"),
    path("seed-tasks/", SeedTasksView.as_view(), name="seed-tasks"),
    path("assign-daily-tasks/", AssignDailyTasksView.as_view(), name="assign-daily-tasks"),
    path("daily-tasks/", DailyTasksView.as_view(), name="daily-tasks"),
    path("journal/", JournalView.as_view(), name="journal"),
    path("journal/history/", JournalHistoryView.as_view(), name="journal-history"),
    path("leaderboard/", LeaderboardView.as_view(), name="leaderboard"),
    path("weekly-report/", WeeklyWarReportView.as_view(), name="weekly-report"),
    path("push/subscribe/", PushSubscriptionView.as_view(), name="push-subscribe"),
]
